version: "3.8"
services:
  backend:
    container_name: backend
    ports:
      - 4000:4000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    build:
      context: backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stopwatch
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stopwatch
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/ópostgresql/data

volumes:
  data:
